import { Data, IProductInput, IUserInput } from "@/types";
import { toSlug } from "./utils";
import bcrypt from "bcryptjs";
import {
  IMG1,
  IMG2,
  IMG4,
  IMG6,
  IMG7,
  IMG8,
  IMG9,
  IMG11,
  IMG12,
  IMG13,
  IMG15,
  IMG16,
  IMG17,
  IMG18,
  IMG19,
  IMG20,
  IMG21,
  IMG22,
  IMG23,
  IMG24,
  IMG25,
  IMG26,
  IMG27,
  IMG10,
  IMG3,
} from "@/constant/assets";

// small helpers to keep seed data clear and robust
const hash = (pw: string) => bcrypt.hashSync(pw, 5);

const users: IUserInput[] = [
  {
    name: "Vitech",
    email: "admin@example.com",
    password: hash("123456"),
    role: "Admin",
    address: {
      firstName: "John Doe",
      middleName: "",
      lastName: "",
      street: "111 Main St",
      city: "Accra",
      province: "Greater Accra",
      postalCode: "10001",
      country: "Ghana",
      phone: "123-456-7890",
    },
    paymentMethod: "Stripe",
    emailVerified: false,
  },
  {
    name: "Jane",
    email: "jane@example.com",
    password: hash("123456"),
    role: "User",
    address: {
      firstName: "Jane Harris",
      middleName: "",
      lastName: "",
      street: "222 Main St",
      city: "New York",
      province: "NY",
      postalCode: "1002",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Jack",
    email: "jack@example.com",
    password: hash("123456"),
    role: "User",
    address: {
      firstName: "Jack Ryan",
      middleName: "",
      lastName: "",
      street: "333 Main St",
      city: "New York",
      province: "NY",
      postalCode: "1003",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "momo",
    emailVerified: false,
  },
  {
    name: "Sarah",
    email: "sarah@example.com",
    password: hash("123456"),
    role: "User",
    address: {
      firstName: "Sarah Smith",
      middleName: "",
      lastName: "",
      street: "444 Main St",
      city: "New York",
      province: "NY",
      postalCode: "1005",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Michael",
    email: "michael@example.com",
    password: hash("123456"),
    role: "User",
    address: {
      firstName: "John Alexander",
      middleName: "",
      lastName: "",
      street: "555 Main St",
      city: "New York",
      province: "NY",
      postalCode: "1006",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "momo",
    emailVerified: false,
  },
  {
    name: "Emily",
    email: "emily@example.com",
    password: hash("123456"),
    role: "User",
    address: {
      firstName: "Emily Johnson",
      middleName: "",
      lastName: "",
      street: "666 Main St",
      city: "New York",
      province: "NY",
      postalCode: "10001",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Stripe",
    emailVerified: false,
  },
  {
    name: "Alice",
    email: "alice@example.com",
    password: hash("123456"),
    role: "User",
    address: {
      firstName: "Alice Cooper",
      middleName: "",
      lastName: "",
      street: "777 Main St",
      city: "New York",
      province: "NY",
      postalCode: "10007",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Tom",
    email: "tom@example.com",
    password: hash("123456"),
    role: "User",
    address: {
      firstName: "Tom Hanks",
      middleName: "",
      lastName: "",
      street: "888 Main St",
      city: "New York",
      province: "NY",
      postalCode: "10008",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Stripe",
    emailVerified: false,
  },
  {
    name: "Linda",
    email: "linda@example.com",
    password: hash("123456"),
    role: "User",
    address: {
      firstName: "Linda Holmes",
      middleName: "",
      lastName: "",
      street: "999 Main St",
      city: "New York",
      province: "NY",
      postalCode: "10009",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "momo",
    emailVerified: false,
  },
  {
    name: "George",
    email: "george@example.com",
    password: hash("123456"),
    role: "User",
    address: {
      firstName: "George Smith",
      middleName: "",
      lastName: "",
      street: "101 First Ave",
      city: "New York",
      province: "NY",
      postalCode: "10010",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Stripe",
    emailVerified: false,
  },
  {
    name: "Jessica",
    email: "jessica@example.com",
    password: hash("123456"),
    role: "User",
    address: {
      firstName: "Jessica Brown",
      middleName: "",
      lastName: "",
      street: "102 First Ave",
      city: "New York",
      province: "NY",
      postalCode: "10011",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Chris",
    email: "chris@example.com",
    password: hash("123456"),
    role: "User",
    address: {
      firstName: "Chris Evans",
      middleName: "",
      lastName: "",
      street: "103 First Ave",
      city: "New York",
      province: "NY",
      postalCode: "10012",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "momo",
    emailVerified: false,
  },
  {
    name: "Samantha",
    email: "samantha@example.com",
    password: hash("123456"),
    role: "User",
    address: {
      firstName: "Samantha Wilson",
      middleName: "",
      lastName: "",
      street: "104 First Ave",
      city: "New York",
      province: "NY",
      postalCode: "10013",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "Stripe",
    emailVerified: false,
  },
  {
    name: "David",
    email: "david@example.com",
    password: hash("123456"),
    role: "User",
    address: {
      firstName: "David Lee",
      middleName: "",
      lastName: "",
      street: "105 First Ave",
      city: "New York",
      province: "Greater Accra",
      postalCode: "10014",
      country: "Ghana",
      phone: "123-456-7890",
    },
    paymentMethod: "Cash On Delivery",
    emailVerified: false,
  },
  {
    name: "Anna",
    email: "anna@example.com",
    password: hash("123456"),
    role: "User",
    address: {
      firstName: "Anna Smith",
      middleName: "",
      lastName: "",
      street: "106 First Ave",
      city: "New York",
      province: "NY",
      postalCode: "10015",
      country: "USA",
      phone: "123-456-7890",
    },
    paymentMethod: "momo",
    emailVerified: false,
  },
];

export const products: IProductInput[] = [
  // ----- WOMEN PERFUMES -----
  {
    name: "Nasy Bloom Eau de Parfum",
    slug: toSlug("Nasy Bloom Eau de Parfum"),
    category: "Perfume",
    subcategory: "Women",
    description:
      "A floral fragrance combining jasmine, rose, and vanilla for timeless elegance.",
    price: 180,
    listPrice: 220,
    stock: "15",
    brand: "Nasy",
    countInStock: 15,
    featured: true,
    newArrival: true,
    isPublished: true,
    images: [IMG1, IMG26],
    tags: ["floral", "sweet", "romantic"],
    sizes: [],
    colors: [],
    avgRating: 4.5,
    numReviews: 12,
    ratingDistribution: [
      { rating: 5, count: 8 },
      { rating: 4, count: 4 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 25,
  },

  {
    name: "Nasy  de Parfum",
    slug: toSlug("Nasy Parfum"),
    category: "Perfume",
    subcategory: "Women",
    description:
      "A floral fragrance combining jasmine, rose, and vanilla for timeless elegance.",
    price: 10,
    listPrice: 20,
    stock: "15",
    brand: "Nasy",
    countInStock: 15,
    featured: true,
    newArrival: true,
    isPublished: true,
    images: [IMG6, IMG26],
    tags: ["floral", "sweet", "romantic"],
    sizes: [],
    colors: [],
    avgRating: 4.5,
    numReviews: 12,
    ratingDistribution: [
      { rating: 5, count: 8 },
      { rating: 4, count: 4 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 25,
  },

  {
    name: "Nasy Bloom Eau de Parfum",
    slug: toSlug("Eau de Parfum"),
    category: "Perfume",
    subcategory: "Women",
    description:
      "A floral fragrance combining jasmine, rose, and vanilla for timeless elegance.",
    price: 80,
    listPrice: 22,
    stock: "15",
    brand: "Nasy",
    countInStock: 15,
    featured: true,
    newArrival: true,
    isPublished: true,
    images: [IMG3, IMG4],
    tags: ["floral", "sweet", "romantic"],
    sizes: [],
    colors: [],
    avgRating: 4.5,
    numReviews: 12,
    ratingDistribution: [
      { rating: 5, count: 8 },
      { rating: 4, count: 4 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 25,
  },

  {
    name: "Nasy Bloom Eau de Parfum",
    slug: toSlug("Nasy Parfum"),
    category: "Perfume",
    subcategory: "Women",
    description:
      "A floral fragrance combining jasmine, rose, and vanilla for timeless elegance.",
    price: 3,
    listPrice: 0,
    stock: "15",
    brand: "Nasy",
    countInStock: 15,
    featured: true,
    newArrival: true,
    isPublished: true,
    images: [IMG26],
    tags: ["floral", "sweet", "romantic"],
    sizes: [],
    colors: [],
    avgRating: 4.5,
    numReviews: 12,
    ratingDistribution: [
      { rating: 5, count: 8 },
      { rating: 4, count: 4 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 25,
  },

  {
    name: "Nasy Bloom Eau de Parfum",
    slug: toSlug("Nasy Bloom"),
    category: "Perfume",
    subcategory: "Women",
    description:
      "A floral fragrance combining jasmine, rose, and vanilla for timeless elegance.",
    price: 66,
    listPrice: 220,
    stock: "15",
    brand: "Nasy",
    countInStock: 15,
    featured: true,
    newArrival: true,
    isPublished: true,
    images: [IMG4],
    tags: ["floral", "sweet", "romantic"],
    sizes: [],
    colors: [],
    avgRating: 4.5,
    numReviews: 12,
    ratingDistribution: [
      { rating: 5, count: 8 },
      { rating: 4, count: 4 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 25,
  },

  {
    name: "Nasy Bloom Eau de Parfum",
    slug: toSlug("perfume a ettdf"),
    category: "Perfume",
    subcategory: "Women",
    description:
      "A floral fragrance combining jasmine, rose, and vanilla for timeless elegance.",
    price: 10,
    listPrice: 220,
    stock: "15",
    brand: "Nasy",
    countInStock: 15,
    featured: true,
    newArrival: true,
    isPublished: true,
    images: [IMG16],
    tags: ["floral", "sweet", "romantic"],
    sizes: [],
    colors: [],
    avgRating: 4.5,
    numReviews: 12,
    ratingDistribution: [
      { rating: 5, count: 8 },
      { rating: 4, count: 4 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 25,
  },

  {
    name: "Nasy Bloom Eau de Parfum",
    slug: toSlug("Bloom"),
    category: "Perfume",
    subcategory: "Women",
    description:
      "A floral fragrance combining jasmine, rose, and vanilla for timeless elegance.",
    price: 6,
    listPrice: 220,
    stock: "15",
    brand: "Nasy",
    countInStock: 15,
    featured: true,
    newArrival: true,
    isPublished: true,
    images: [IMG10],
    tags: ["floral", "sweet", "romantic"],
    sizes: [],
    colors: [],
    avgRating: 4.5,
    numReviews: 12,
    ratingDistribution: [
      { rating: 5, count: 8 },
      { rating: 4, count: 4 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 25,
  },
  {
    name: "Velvet Mist Eau de Toilette",
    slug: toSlug("Velvet Mist Eau de Toilette"),
    category: "Perfume",
    subcategory: "Women",
    description:
      "Soft, powdery notes of iris and sandalwood blend for a sophisticated aura.",
    price: 15,
    listPrice: 180,
    stock: "20",
    brand: "Velvet",
    countInStock: 20,
    featured: false,
    newArrival: false,
    isPublished: true,
    images: [IMG15, IMG16, IMG17, IMG18],
    tags: ["soft", "powdery"],
    sizes: [],
    colors: [],
    avgRating: 4.0,
    numReviews: 8,
    ratingDistribution: [
      { rating: 5, count: 3 },
      { rating: 4, count: 5 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 18,
  },

  // ----- MEN PERFUMES -----
  {
    name: "Nasy Noir Intense",
    slug: toSlug("Nasy Noir Intense"),
    category: "Perfume",
    subcategory: "Men",
    description:
      "Woody and smoky accords layered with leather and vetiver — bold and refined.",
    price: 50,
    listPrice: 300,
    stock: "8",
    brand: "Nasy",
    countInStock: 8,
    featured: true,
    newArrival: false,
    isPublished: true,
    images: [IMG4, IMG27],
    tags: ["woody", "leather", "smoky"],
    sizes: [],
    colors: [],
    avgRating: 4.7,
    numReviews: 14,
    ratingDistribution: [
      { rating: 5, count: 10 },
      { rating: 4, count: 4 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 30,
  },
  {
    name: "Nasy Noir Intense",
    slug: toSlug("Nasy  Intense"),
    category: "Perfume",
    subcategory: "Men",
    description:
      "Woody and smoky accords layered with leather and vetiver — bold and refined.",
    price: 25,
    listPrice: 300,
    stock: "8",
    brand: "Nasy",
    countInStock: 8,
    featured: true,
    newArrival: false,
    isPublished: true,
    images: [IMG22, IMG27],
    tags: ["woody", "leather", "smoky"],
    sizes: [],
    colors: [],
    avgRating: 4.7,
    numReviews: 14,
    ratingDistribution: [
      { rating: 5, count: 10 },
      { rating: 4, count: 4 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 30,
  },
  {
    name: "Nasy Noir Intense",
    slug: toSlug("Nasy Noir"),
    category: "Perfume",
    subcategory: "Men",
    description:
      "Woody and smoky accords layered with leather and vetiver — bold and refined.",
    price: 250,
    listPrice: 300,
    stock: "8",
    brand: "Nasy",
    countInStock: 8,
    featured: true,
    newArrival: false,
    isPublished: true,
    images: [IMG20, IMG21],
    tags: ["woody", "leather", "smoky"],
    sizes: [],
    colors: [],
    avgRating: 4.7,
    numReviews: 14,
    ratingDistribution: [
      { rating: 5, count: 10 },
      { rating: 4, count: 4 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 30,
  },
  {
    name: "Nasy Noir Intense",
    slug: toSlug(" Intense"),
    category: "Perfume",
    subcategory: "Men",
    description:
      "Woody and smoky accords layered with leather and vetiver — bold and refined.",
    price: 20,
    listPrice: 300,
    stock: "8",
    brand: "Nasy",
    countInStock: 8,
    featured: true,
    newArrival: false,
    isPublished: true,
    images: [IMG27],
    tags: ["woody", "leather", "smoky"],
    sizes: [],
    colors: [],
    avgRating: 4.7,
    numReviews: 14,
    ratingDistribution: [
      { rating: 5, count: 10 },
      { rating: 4, count: 4 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 30,
  },
  {
    name: "Nasy Noir Intense",
    slug: toSlug("Nasy tujw ddj"),
    category: "Perfume",
    subcategory: "Men",
    description:
      "Woody and smoky accords layered with leather and vetiver — bold and refined.",
    price: 5,
    listPrice: 300,
    stock: "8",
    brand: "Nasy",
    countInStock: 8,
    featured: true,
    newArrival: false,
    isPublished: true,
    images: [IMG20, IMG21],
    tags: ["woody", "leather", "smoky"],
    sizes: [],
    colors: [],
    avgRating: 4.7,
    numReviews: 14,
    ratingDistribution: [
      { rating: 5, count: 10 },
      { rating: 4, count: 4 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 30,
  },
  {
    name: "Nasy Noir Intense",
    slug: toSlug("SKffnerdc"),
    category: "Perfume",
    subcategory: "Men",
    description:
      "Woody and smoky accords layered with leather and vetiver — bold and refined.",
    price: 250,
    listPrice: 300,
    stock: "8",
    brand: "Nasy",
    countInStock: 8,
    featured: true,
    newArrival: false,
    isPublished: true,
    images: [IMG4, IMG19, IMG20, IMG21, IMG22, IMG27],
    tags: ["woody", "leather", "smoky"],
    sizes: [],
    colors: [],
    avgRating: 4.7,
    numReviews: 14,
    ratingDistribution: [
      { rating: 5, count: 10 },
      { rating: 4, count: 4 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 30,
  },
  {
    name: "Nasy Noir Intense",
    slug: toSlug("Ejdhufjfjdd"),
    category: "Perfume",
    subcategory: "Men",
    description:
      "Woody and smoky accords layered with leather and vetiver — bold and refined.",
    price: 250,
    listPrice: 300,
    stock: "8",
    brand: "Nasy",
    countInStock: 8,
    featured: true,
    newArrival: false,
    isPublished: true,
    images: [IMG4, IMG19, IMG20, IMG21, IMG22, IMG27],
    tags: ["woody", "leather", "smoky"],
    sizes: [],
    colors: [],
    avgRating: 4.7,
    numReviews: 14,
    ratingDistribution: [
      { rating: 5, count: 10 },
      { rating: 4, count: 4 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 30,
  },
  {
    name: "Cedar Pulse Cologne",
    slug: toSlug("Cedar Pulse Cologne"),
    category: "Perfume",
    subcategory: "Men",
    description: "A rugged yet elegant mix of cedarwood, pepper, and bergamot.",
    price: 175,
    listPrice: 200,
    stock: "25",
    brand: "Cedar",
    countInStock: 25,
    featured: false,
    newArrival: true,
    isPublished: true,
    images: [IMG6, IMG7, IMG8, IMG23, IMG24, IMG25],
    tags: ["woody", "spicy"],
    sizes: [],
    colors: [],
    avgRating: 4.2,
    numReviews: 9,
    ratingDistribution: [
      { rating: 5, count: 5 },
      { rating: 4, count: 4 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 20,
  },

  // ----- KIDS -----
  {
    name: "Kids Gentle Foam Wash",
    slug: toSlug("Kids Gentle Foam Wash"),
    category: "Kids",
    subcategory: "Bath Soap",
    description:
      "Tear-free gentle foam soap made with chamomile and lavender for kids.",
    price: 40,
    listPrice: 50,
    stock: "25",
    brand: "Nasy Kids",
    countInStock: 25,
    featured: false,
    newArrival: true,
    isPublished: true,
    images: [IMG11, IMG12, IMG13, IMG15, IMG16],
    tags: ["gentle", "foam", "kids"],
    sizes: [],
    colors: [],
    avgRating: 4.8,
    numReviews: 5,
    ratingDistribution: [
      { rating: 5, count: 5 },
      { rating: 4, count: 0 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 12,
  },

  {
    name: "Kids Gentle Foam Wash",
    slug: toSlug("Kids Foam Wash"),
    category: "Kids",
    subcategory: "Bath Soap",
    description:
      "Tear-free gentle foam soap made with chamomile and lavender for kids.",
    price: 40,
    listPrice: 50,
    stock: "25",
    brand: "Nasy Kids",
    countInStock: 25,
    featured: false,
    newArrival: true,
    isPublished: true,
    images: [IMG12],
    tags: ["gentle", "foam", "kids"],
    sizes: [],
    colors: [],
    avgRating: 4.8,
    numReviews: 5,
    ratingDistribution: [
      { rating: 5, count: 5 },
      { rating: 4, count: 0 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 12,
  },

  {
    name: "Kids Gentle Foam Wash",
    slug: toSlug("Kids Wash"),
    category: "Kids",
    subcategory: "Bath Soap",
    description:
      "Tear-free gentle foam soap made with chamomile and lavender for kids.",
    price: 40,
    listPrice: 50,
    stock: "25",
    brand: "Nasy Kids",
    countInStock: 25,
    featured: false,
    newArrival: true,
    isPublished: true,
    images: [IMG13],
    tags: ["gentle", "foam", "kids"],
    sizes: [],
    colors: [],
    avgRating: 4.8,
    numReviews: 5,
    ratingDistribution: [
      { rating: 5, count: 5 },
      { rating: 4, count: 0 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 12,
  },

  {
    name: "Kids Gentle Foam Wash",
    slug: toSlug("Kids hands Wash"),
    category: "Kids",
    subcategory: "Bath Soap",
    description:
      "Tear-free gentle foam soap made with chamomile and lavender for kids.",
    price: 40,
    listPrice: 50,
    stock: "25",
    brand: "Nasy Kids",
    countInStock: 25,
    featured: false,
    newArrival: true,
    isPublished: true,
    images: [IMG15, IMG16],
    tags: ["gentle", "foam", "kids"],
    sizes: [],
    colors: [],
    avgRating: 4.8,
    numReviews: 5,
    ratingDistribution: [
      { rating: 5, count: 5 },
      { rating: 4, count: 0 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 12,
  },

  {
    name: "Kids Gentle Foam Wash",
    slug: toSlug(" Gentle Foam Wash"),
    category: "Kids",
    subcategory: "Bath Soap",
    description:
      "Tear-free gentle foam soap made with chamomile and lavender for kids.",
    price: 40,
    listPrice: 50,
    stock: "25",
    brand: "Nasy Kids",
    countInStock: 25,
    featured: false,
    newArrival: true,
    isPublished: true,
    images: [IMG16],
    tags: ["gentle", "foam", "kids"],
    sizes: [],
    colors: [],
    avgRating: 4.8,
    numReviews: 5,
    ratingDistribution: [
      { rating: 5, count: 5 },
      { rating: 4, count: 0 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 12,
  },

  {
    name: "Kids Gentle Foam Wash",
    slug: toSlug("Foam Wash"),
    category: "Kids",
    subcategory: "Bath Soap",
    description:
      "Tear-free gentle foam soap made with chamomile and lavender for kids.",
    price: 40,
    listPrice: 50,
    stock: "25",
    brand: "Nasy Kids",
    countInStock: 25,
    featured: false,
    newArrival: true,
    isPublished: true,
    images: [IMG17],
    tags: ["gentle", "foam", "kids"],
    sizes: [],
    colors: [],
    avgRating: 4.8,
    numReviews: 5,
    ratingDistribution: [
      { rating: 5, count: 5 },
      { rating: 4, count: 0 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 12,
  },

  {
    name: "Kids Gentle Foam Wash",
    slug: toSlug("Kids Gentle "),
    category: "Kids",
    subcategory: "Bath Soap",
    description:
      "Tear-free gentle foam soap made with chamomile and lavender for kids.",
    price: 40,
    listPrice: 50,
    stock: "25",
    brand: "Nasy Kids",
    countInStock: 25,
    featured: false,
    newArrival: true,
    isPublished: true,
    images: [IMG1],
    tags: ["gentle", "foam", "kids"],
    sizes: [],
    colors: [],
    avgRating: 4.8,
    numReviews: 5,
    ratingDistribution: [
      { rating: 5, count: 5 },
      { rating: 4, count: 0 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 12,
  },

  {
    name: "Kids Gentle Foam Wash",
    slug: toSlug("kis Foam Wash"),
    category: "Kids",
    subcategory: "Bath Soap",
    description:
      "Tear-free gentle foam soap made with chamomile and lavender for kids.",
    price: 40,
    listPrice: 50,
    stock: "25",
    brand: "Nasy Kids",
    countInStock: 25,
    featured: false,
    newArrival: true,
    isPublished: true,
    images: [IMG18],
    tags: ["gentle", "foam", "kids"],
    sizes: [],
    colors: [],
    avgRating: 4.8,
    numReviews: 5,
    ratingDistribution: [
      { rating: 5, count: 5 },
      { rating: 4, count: 0 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 12,
  },

  // ----- BODY CARE / SANITARY -----
  {
    name: "Nasy Liquid Bath Soap - Vanilla Cream",
    slug: toSlug("Nasy Liquid Bath Soap - Vanilla Cream"),
    category: "Body Care",
    subcategory: "Bath Soap",
    description:
      "Enriched with shea butter and vanilla for a silky smooth bath experience.",
    price: 45,
    listPrice: 55,
    stock: "40",
    brand: "Nasy",
    countInStock: 40,
    featured: true,
    newArrival: false,
    isPublished: true,
    images: [IMG9, IMG10, IMG11, IMG12, IMG13],
    tags: ["vanilla", "shea"],
    sizes: [],
    colors: [],
    avgRating: 4.4,
    numReviews: 7,
    ratingDistribution: [
      { rating: 5, count: 4 },
      { rating: 4, count: 3 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 22,
  },

  {
    name: "Nasy Liquid Bath Soap - Vanilla Cream",
    slug: toSlug(" Liquid Bath Soap - Vanilla Cream"),
    category: "Body Care",
    subcategory: "Bath Soap",
    description:
      "Enriched with shea butter and vanilla for a silky smooth bath experience.",
    price: 45,
    listPrice: 55,
    stock: "40",
    brand: "Nasy",
    countInStock: 40,
    featured: true,
    newArrival: false,
    isPublished: true,
    images: [IMG11],
    tags: ["vanilla", "shea"],
    sizes: [],
    colors: [],
    avgRating: 4.4,
    numReviews: 7,
    ratingDistribution: [
      { rating: 5, count: 4 },
      { rating: 4, count: 3 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 22,
  },

  {
    name: "Nasy Liquid Bath Soap - Vanilla Cream",
    slug: toSlug("Nasy  Bath Soap - Vanilla Cream"),
    category: "Body Care",
    subcategory: "Bath Soap",
    description:
      "Enriched with shea butter and vanilla for a silky smooth bath experience.",
    price: 45,
    listPrice: 55,
    stock: "40",
    brand: "Nasy",
    countInStock: 40,
    featured: true,
    newArrival: false,
    isPublished: true,
    images: [IMG13],
    tags: ["vanilla", "shea"],
    sizes: [],
    colors: [],
    avgRating: 4.4,
    numReviews: 7,
    ratingDistribution: [
      { rating: 5, count: 4 },
      { rating: 4, count: 3 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 22,
  },

  {
    name: "Nasy Liquid Bath Soap - Vanilla Cream",
    slug: toSlug("Nasy Liquid  Soap - Vanilla Cream"),
    category: "Body Care",
    subcategory: "Bath Soap",
    description:
      "Enriched with shea butter and vanilla for a silky smooth bath experience.",
    price: 45,
    listPrice: 55,
    stock: "40",
    brand: "Nasy",
    countInStock: 40,
    featured: true,
    newArrival: false,
    isPublished: true,
    images: [IMG25],
    tags: ["vanilla", "shea"],
    sizes: [],
    colors: [],
    avgRating: 4.4,
    numReviews: 7,
    ratingDistribution: [
      { rating: 5, count: 4 },
      { rating: 4, count: 3 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 22,
  },

  {
    name: "Nasy Liquid Bath Soap - Vanilla Cream",
    slug: toSlug("Nasy Liquid Bath  - Vanilla Cream"),
    category: "Body Care",
    subcategory: "Bath Soap",
    description:
      "Enriched with shea butter and vanilla for a silky smooth bath experience.",
    price: 45,
    listPrice: 55,
    stock: "40",
    brand: "Nasy",
    countInStock: 40,
    featured: true,
    newArrival: false,
    isPublished: true,
    images: [IMG12],
    tags: ["vanilla", "shea"],
    sizes: [],
    colors: [],
    avgRating: 4.4,
    numReviews: 7,
    ratingDistribution: [
      { rating: 5, count: 4 },
      { rating: 4, count: 3 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 22,
  },

  {
    name: "Nasy Liquid Bath Soap - Vanilla Cream",
    slug: toSlug("Nasy Liquid Bath Soap -  Cream"),
    category: "Body Care",
    subcategory: "Bath Soap",
    description:
      "Enriched with shea butter and vanilla for a silky smooth bath experience.",
    price: 45,
    listPrice: 55,
    stock: "40",
    brand: "Nasy",
    countInStock: 40,
    featured: true,
    newArrival: false,
    isPublished: true,
    images: [IMG24],
    tags: ["vanilla", "shea"],
    sizes: [],
    colors: [],
    avgRating: 4.4,
    numReviews: 7,
    ratingDistribution: [
      { rating: 5, count: 4 },
      { rating: 4, count: 3 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 22,
  },

  {
    name: "Nasy Liquid Bath Soap - Vanilla Cream",
    slug: toSlug("Nasy Liquid Bath Soap - Vanilla"),
    category: "Body Care",
    subcategory: "Bath Soap",
    description:
      "Enriched with shea butter and vanilla for a silky smooth bath experience.",
    price: 45,
    listPrice: 55,
    stock: "40",
    brand: "Nasy",
    countInStock: 40,
    featured: true,
    newArrival: false,
    isPublished: true,
    images: [IMG20],
    tags: ["vanilla", "shea"],
    sizes: [],
    colors: [],
    avgRating: 4.4,
    numReviews: 7,
    ratingDistribution: [
      { rating: 5, count: 4 },
      { rating: 4, count: 3 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 22,
  },

  {
    name: "Nasy Liquid Bath Soap - Vanilla Cream",
    slug: toSlug("Nasy Liquid Bath Soap"),
    category: "Body Care",
    subcategory: "Bath Soap",
    description:
      "Enriched with shea butter and vanilla for a silky smooth bath experience.",
    price: 45,
    listPrice: 55,
    stock: "40",
    brand: "Nasy",
    countInStock: 40,
    featured: true,
    newArrival: false,
    isPublished: true,
    images: [IMG22],
    tags: ["vanilla", "shea"],
    sizes: [],
    colors: [],
    avgRating: 4.4,
    numReviews: 7,
    ratingDistribution: [
      { rating: 5, count: 4 },
      { rating: 4, count: 3 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 22,
  },

  //   Hygiene
  {
    name: "Nasy Sanitary Pad - Ultra Comfort (10pcs)",
    slug: toSlug("Nasy Sanitary Pad - Ultra Comfort (10pcs)"),
    category: "Hygiene",
    subcategory: "Women",
    description:
      "Soft cotton top layer and leak-proof design for all-day freshness.",
    price: 35,
    listPrice: 40,
    stock: "50",
    brand: "Nasy",
    countInStock: 50,
    featured: false,
    newArrival: true,
    isPublished: true,
    images: [IMG12, IMG13, IMG18, IMG15, IMG16],
    tags: ["sanitary", "cotton", "comfort"],
    sizes: [],
    colors: [],
    avgRating: 4.6,
    numReviews: 10,
    ratingDistribution: [
      { rating: 5, count: 7 },
      { rating: 4, count: 3 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 35,
  },

  {
    name: "Nasy Sanitary Pad - Ultra Comfort (10pcs)",
    slug: toSlug(" Sanitary Pad - Ultra Comfort (10pcs)"),
    category: "Hygiene",
    subcategory: "Women",
    description:
      "Soft cotton top layer and leak-proof design for all-day freshness.",
    price: 35,
    listPrice: 40,
    stock: "50",
    brand: "Nasy",
    countInStock: 50,
    featured: false,
    newArrival: true,
    isPublished: true,
    images: [IMG16],
    tags: ["sanitary", "cotton", "comfort"],
    sizes: [],
    colors: [],
    avgRating: 4.6,
    numReviews: 10,
    ratingDistribution: [
      { rating: 5, count: 7 },
      { rating: 4, count: 3 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 35,
  },

  {
    name: "Nasy Sanitary Pad - Ultra Comfort (10pcs)",
    slug: toSlug("Nasy  Pad - Ultra Comfort (10pcs)"),
    category: "Hygiene",
    subcategory: "Women",
    description:
      "Soft cotton top layer and leak-proof design for all-day freshness.",
    price: 35,
    listPrice: 40,
    stock: "50",
    brand: "Nasy",
    countInStock: 50,
    featured: false,
    newArrival: true,
    isPublished: true,
    images: [IMG15, IMG16],
    tags: ["sanitary", "cotton", "comfort"],
    sizes: [],
    colors: [],
    avgRating: 4.6,
    numReviews: 10,
    ratingDistribution: [
      { rating: 5, count: 7 },
      { rating: 4, count: 3 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 35,
  },

  {
    name: "Nasy Sanitary Pad - Ultra Comfort (10pcs)",
    slug: toSlug("Nasy Sanitary Padd - Ultra Comfort (10pcs)"),
    category: "Hygiene",
    subcategory: "Women",
    description:
      "Soft cotton top layer and leak-proof design for all-day freshness.",
    price: 35,
    listPrice: 40,
    stock: "50",
    brand: "Nasy",
    countInStock: 50,
    featured: false,
    newArrival: true,
    isPublished: true,
    images: [IMG23],
    tags: ["sanitary", "cotton", "comfort"],
    sizes: [],
    colors: [],
    avgRating: 4.6,
    numReviews: 10,
    ratingDistribution: [
      { rating: 5, count: 7 },
      { rating: 4, count: 3 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 35,
  },

  {
    name: "Nasy Sanitary Pad - Ultra Comfort (10pcs)",
    slug: toSlug("Nasy Sanitary Pad -  Comfort"),
    category: "Hygiene",
    subcategory: "Women",
    description:
      "Soft cotton top layer and leak-proof design for all-day freshness.",
    price: 35,
    listPrice: 40,
    stock: "50",
    brand: "Nasy",
    countInStock: 50,
    featured: false,
    newArrival: true,
    isPublished: true,
    images: [IMG20],
    tags: ["sanitary", "cotton", "comfort"],
    sizes: [],
    colors: [],
    avgRating: 4.6,
    numReviews: 10,
    ratingDistribution: [
      { rating: 5, count: 7 },
      { rating: 4, count: 3 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 35,
  },

  {
    name: "Nasy Sanitary Pad - Ultra Comfort (10pcs)",
    slug: toSlug(" Sanitary  - Ultra Comfort (10pcs)"),
    category: "Hygiene",
    subcategory: "Women",
    description:
      "Soft cotton top layer and leak-proof design for all-day freshness.",
    price: 35,
    listPrice: 40,
    stock: "50",
    brand: "Nasy",
    countInStock: 50,
    featured: false,
    newArrival: true,
    isPublished: true,
    images: [IMG24],
    tags: ["sanitary", "cotton", "comfort"],
    sizes: [],
    colors: [],
    avgRating: 4.6,
    numReviews: 10,
    ratingDistribution: [
      { rating: 5, count: 7 },
      { rating: 4, count: 3 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 35,
  },

  {
    name: "Nasy Sanitary Pad - Ultra Comfort (10pcs)",
    slug: toSlug("Nasy Sanitary Pad"),
    category: "Hygiene",
    subcategory: "Women",
    description:
      "Soft cotton top layer and leak-proof design for all-day freshness.",
    price: 35,
    listPrice: 40,
    stock: "50",
    brand: "Nasy",
    countInStock: 50,
    featured: false,
    newArrival: true,
    isPublished: true,
    images: [IMG2],
    tags: ["sanitary", "cotton", "comfort"],
    sizes: [],
    colors: [],
    avgRating: 4.6,
    numReviews: 10,
    ratingDistribution: [
      { rating: 5, count: 7 },
      { rating: 4, count: 3 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 35,
  },

  {
    name: "Nasy Sanitary Pad - Ultra Comfort (10pcs)",
    slug: toSlug("Nasy Sanitary Padd"),
    category: "Hygiene",
    subcategory: "Women",
    description:
      "Soft cotton top layer and leak-proof design for all-day freshness.",
    price:50,
    listPrice: 40,
    stock: "0",
    brand: "Nasy",
    countInStock: 0,
    featured: false,
    newArrival: true,
    isPublished: true,
    images: [IMG27],
    tags: ["sanitary", "cotton", "comfort"],
    sizes: [],
    colors: [],
    avgRating: 4.6,
    numReviews: 10,
    ratingDistribution: [
      { rating: 5, count: 7 },
      { rating: 4, count: 3 },
      { rating: 3, count: 0 },
      { rating: 2, count: 0 },
      { rating: 1, count: 0 },
    ],
    reviews: [],
    numSales: 35,
  },
];

const reviews = [
  {
    rating: 1,
    title: "Poor quality",
    comment:
      "Very disappointed. The item broke after just a few uses. Not worth the money.",
  },
  {
    rating: 2,
    title: "Disappointed",
    comment:
      "Not as expected. The material feels cheap, and it didn't fit well. Wouldn't buy again.",
  },
  {
    rating: 2,
    title: "Needs improvement",
    comment:
      "It looks nice but doesn't perform as expected. Wouldn't recommend without upgrades.",
  },
  {
    rating: 3,
    title: "not bad",
    comment:
      "This product is decent, the quality is good but it could use some improvements in the details.",
  },
  {
    rating: 3,
    title: "Okay, not great",
    comment:
      "It works, but not as well as I hoped. Quality is average and lacks some finishing.",
  },
  {
    rating: 3,
    title: "Good product",
    comment:
      "This product is amazing, I love it! The quality is top notch, the material is comfortable and breathable.",
  },
  {
    rating: 4,
    title: "Pretty good",
    comment:
      "Solid product! Great value for the price, but there's room for minor improvements.",
  },
  {
    rating: 4,
    title: "Very satisfied",
    comment:
      "Good product! High quality and worth the price. Would consider buying again.",
  },
  {
    rating: 4,
    title: "Absolutely love it!",
    comment:
      "Perfect in every way! The quality, design, and comfort exceeded all my expectations.",
  },
  {
    rating: 4,
    title: "Exceeded expectations!",
    comment:
      "Fantastic product! High quality, feels durable, and performs well. Highly recommend!",
  },
  {
    rating: 5,
    title: "Perfect purchase!",
    comment:
      "Couldn't be happier with this product. The quality is excellent, and it works flawlessly!",
  },
  {
    rating: 5,
    title: "Highly recommend",
    comment:
      "Amazing product! Worth every penny, great design, and feels premium. I'm very satisfied.",
  },
  {
    rating: 5,
    title: "Just what I needed",
    comment:
      "Exactly as described! Quality exceeded my expectations, and it arrived quickly.",
  },
  {
    rating: 5,
    title: "Excellent choice!",
    comment:
      "This product is outstanding! Everything about it feels top-notch, from material to functionality.",
  },
  {
    rating: 5,
    title: "Couldn't ask for more!",
    comment:
      "Love this product! It's durable, stylish, and works great. Would buy again without hesitation.",
  },
];

const data: Data = {
  users,
  products,
  reviews,
  webPage: [
    {
      title: "About Us",
      slug: "about-us",
      content: `Welcome to Blessed Redeemer Fashion and Design, your trusted destination for quality products and exceptional service. Our journey began with a mission to bring you the best shopping experience by offering a wide range of products at competitive prices, all in one convenient platform.

At Blessed Redeemer Fashion and Design, we prioritize customer satisfaction and innovation. Our team works tirelessly to curate a diverse selection of items, from everyday essentials to exclusive deals, ensuring there's something for everyone. We also strive to make your shopping experience seamless with fast shipping, secure payments, and excellent customer support.

As we continue to grow, our commitment to quality and service remains unwavering. Thank you for choosing [Your Store Name]—we look forward to being a part of your journey and delivering value every step of the way.`,
      isPublished: true,
    },
    {
      title: "Contact Us",
      slug: "contact-us",
      content: `We’re here to help! If you have any questions, concerns, or feedback, please don’t hesitate to reach out to us. Our team is ready to assist you and ensure you have the best shopping experience.

**Customer Support**
For inquiries about orders, products, or account-related issues, contact our customer support team:
- **Email:** support@example.com
- **Phone:** +1 (123) 456-7890
- **Live Chat:** Available on our website from 9 AM to 6 PM (Monday to Friday).

**Head Office**
For corporate or business-related inquiries, reach out to our headquarters:
- **Address:** 1234 E-Commerce St, Suite 567, Business City, BC 12345
- **Phone:** +1 (987) 654-3210

We look forward to assisting you! Your satisfaction is our priority.
`,
      isPublished: true,
    },
    {
      title: "Help",
      slug: "help",
      content: `Welcome to our Help Center! We're here to assist you with any questions or concerns you may have while shopping with us. Whether you need help with orders, account management, or product inquiries, this page provides all the information you need to navigate our platform with ease.

**Placing and Managing Orders**
Placing an order is simple and secure. Browse our product categories, add items to your cart, and proceed to checkout. Once your order is placed, you can track its status through your account under the "My Orders" section. If you need to modify or cancel your order, please contact us as soon as possible for assistance.

**Shipping and Returns**
We offer a variety of shipping options to suit your needs, including standard and express delivery. For detailed shipping costs and delivery timelines, visit our Shipping Policy page. If you're not satisfied with your purchase, our hassle-free return process allows you to initiate a return within the specified timeframe. Check our Returns Policy for more details.

**Account and Support**
Managing your account is easy. Log in to update your personal information, payment methods, and saved addresses. If you encounter any issues or need further assistance, our customer support team is available via email, live chat, or phone. Visit our Contact Us page for support hours and contact details.`,
      isPublished: true,
    },
    {
      title: "Privacy Policy",
      slug: "privacy-policy",
      content: `We value your privacy and are committed to protecting your personal information. This Privacy Notice explains how we collect, use, and share your data when you interact with our services. By using our platform, you consent to the practices described herein.

We collect data such as your name, email address, and payment details to provide you with tailored services and improve your experience. This information may also be used for marketing purposes, but only with your consent. Additionally, we may share your data with trusted third-party providers to facilitate transactions or deliver products.

Your data is safeguarded through robust security measures to prevent unauthorized access. However, you have the right to access, correct, or delete your personal information at any time. For inquiries or concerns regarding your privacy, please contact our support team.`,
      isPublished: true,
    },
    {
      title: "Conditions of Use",
      slug: "conditions-of-use",
      content: `Welcome to [Ecommerce Website Name]. By accessing or using our website, you agree to comply with and be bound by the following terms and conditions. These terms govern your use of our platform, including browsing, purchasing products, and interacting with any content or services provided. You must be at least 18 years old or have the consent of a parent or guardian to use this website. Any breach of these terms may result in the termination of your access to our platform.

We strive to ensure all product descriptions, pricing, and availability information on our website are accurate. However, errors may occur, and we reserve the right to correct them without prior notice. All purchases are subject to our return and refund policy. By using our site, you acknowledge that your personal information will be processed according to our privacy policy, ensuring your data is handled securely and responsibly. Please review these terms carefully before proceeding with any transactions.
`,
      isPublished: true,
    },
    {
      title: "Customer Service",
      slug: "customer-service",
      content: `At Blessed Redeemer Fashion and Design, our customer service team is here to ensure you have the best shopping experience. Whether you need assistance with orders, product details, or returns, we are committed to providing prompt and helpful support.

If you have questions or concerns, please reach out to us through our multiple contact options:
- **Email:** support@example.com
- **Phone:** +1 (123) 456-7890
- **Live Chat:** Available on our website for instant assistance

We also provide helpful resources such as order tracking, product guides, and FAQs to assist you with common inquiries. Your satisfaction is our priority, and we’re here to resolve any issues quickly and efficiently. Thank you for choosing us!`,
      isPublished: true,
    },
    {
      title: "Returns Policy",
      slug: "returns-policy",
      content: "Returns Policy Content",
      isPublished: true,
    },
    {
      title: "Careers",
      slug: "careers",
      content: "careers Content",
      isPublished: true,
    },
    {
      title: "Blog",
      slug: "blog",
      content: "Blog Content",
      isPublished: true,
    },
    {
      title: "Sell Products",
      slug: "sell",
      content: `Sell Products Content`,
      isPublished: true,
    },
    {
      title: "Become Affiliate",
      slug: "become-affiliate",
      content: "Become Affiliate Content",
      isPublished: true,
    },
    {
      title: "Advertise Your Products",
      slug: "advertise",
      content: "Advertise Your Products",
      isPublished: true,
    },
    {
      title: "Shipping Rates & Policies",
      slug: "shipping",
      content: "Shipping Rates & Policies",
      isPublished: true,
    },
  ],
  headerMenus: [
    {
      name: "Today's Deal",
      href: "/search?tag=todays-deal",
    },
    {
      name: "New Arrivals",
      href: "/search?tag=new-arrival",
    },
    {
      name: "Featured Products",
      href: "/search?tag=featured",
    },
    {
      name: "Best Sellers",
      href: "/search?tag=best-seller",
    },
    {
      name: "Browsing History",
      href: "/#browsing-history",
    },
    {
      name: "Customer Service",
      href: "/page/customer-service",
    },
    {
      name: "About Us",
      href: "/page/about-us",
    },
    {
      name: "Help",
      href: "/page/help",
    },
  ],
  carousels: [
    {
      title: "Most Popular Shoes For Sale",
      buttonCaption: "Shop Now",
      image: "/images/jeans/jeans15.jpg",
      url: "/search?category=Shoes",
      isPublished: true,
    },
    {
      title: "Best Sellers in T-Shirts",
      buttonCaption: "Shop Now",
      image: "/images/shirts/shirt9.jpg",
      url: "/search?category=T-Shirts",
      isPublished: true,
    },
    {
      title: "Best Deals on Wrist Watches",
      buttonCaption: "See More",
      image: "/images/sneak13.jpg",
      url: "/search?category=Wrist Watches",
      isPublished: true,
    },
  ],
  settings: [
    {
      common: {
        freeShippingMinPrice: 35,
        isMaintenanceMode: false,
        defaultTheme: "Light",
        defaultColor: "Gold",
        pageSize: 9,
      },
      site: {
        name: "Blessed Redeemer Fashion & Design",
        description:
          "An online platform for premium fashion and design, offering unique styles and exceptional quality for modern trends.",
        keywords: "Next Ecommerce, Next.js, Tailwind CSS, MongoDB",
        url: "https://blessed-redeemer2-git-main-owusuvictorjnrs-projects.vercel.app",
        logo: "/icons/mylogo.svg",
        slogan: "Spend less, enjoy more.",
        author: "Vitech Solutions",
        copyright: "2025, vitech-solutions, Inc. or its affiliates",
        email: "admin@example.com",
        address: "123, Main Street, Anytown, GH, Zip 12345",
        phone: "+1 (123) 456-7890",
      },
      carousels: [
        {
          title: "Best Sellers in T-Shirts",
          buttonCaption: "Shop Now",
          image: "/images/shirts/shirt9.jpg",
          url: "/search?category=T-Shirts",
        },
        {
          title: "Most Popular Shoes For Sale",
          buttonCaption: "See More",
          image: "/images/sneak13.jpg",
          url: "/search?category=shoes",
        },
        {
          title: "Best Deals on Wrist Watches",
          buttonCaption: "See More",
          image: "/images/banner2.jpg",
          url: "/search?category=Wrist Watches",
        },
      ],
      availableLanguages: [],
      defaultLanguage: "en-US",

      availableCurrencies: [
        {
          name: "United States Dollar",
          code: "USD",
          symbol: "$",
          convertRate: 1,
        },
        { name: "Euro", code: "EUR", symbol: "€", convertRate: 0.96 },
        { name: "UAE Dirham", code: "AED", symbol: "AED", convertRate: 3.67 },
        {
          name: "Ghanaian Cedi",
          code: "GHS",
          symbol: "₵",
          convertRate: 12.5, // Example conversion rate (1 USD = 12.50 GHS)
        },
      ],
      defaultCurrency: "₵",

      availablePaymentMethods: [
        // { name: "Stripe", commission: 0 },
        { name: "Paystack", commission: 0 },
        { name: "Cash On Delivery", commission: 0 },
        { name: "Mobile Money", commission: 0 },
      ],
      defaultPaymentMethod: "Paystack",
      availableDeliveryDates: [
        {
          name: "Tomorrow",
          daysToDeliver: 1,
          shippingPrice: 12.9,
          freeShippingMinPrice: 0,
        },
        {
          name: "Next 3 Days",
          daysToDeliver: 3,
          shippingPrice: 6.9,
          freeShippingMinPrice: 0,
        },
        {
          name: "Next 5 Days",
          daysToDeliver: 5,
          shippingPrice: 4.9,
          freeShippingMinPrice: 35,
        },
      ],
      defaultDeliveryDate: "Next 5 Days",
    },
  ],
};

export default data;
